// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaigns.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCampaignByCode = `-- name: GetCampaignByCode :one
SELECT
    ca.campaign_code,
    ca.campaign_name,
    cv.image_url
FROM campaign ca
JOIN campaign_view cv ON ca.campaign_code = cv.campaign_code
WHERE ca.campaign_code = $1
`

type GetCampaignByCodeRow struct {
	CampaignCode string
	CampaignName string
	ImageUrl     pgtype.Text
}

func (q *Queries) GetCampaignByCode(ctx context.Context, campaignCode string) (GetCampaignByCodeRow, error) {
	row := q.db.QueryRow(ctx, getCampaignByCode, campaignCode)
	var i GetCampaignByCodeRow
	err := row.Scan(&i.CampaignCode, &i.CampaignName, &i.ImageUrl)
	return i, err
}

const getCampaignScenarios = `-- name: GetCampaignScenarios :many
SELECT
    sv.scenario_code,
    sv.scenario_name,
    sv.scenario_prefix,
    sv.position,
    sv.image_url
FROM scenario_view sv
WHERE sv.campaign_code = $1
ORDER BY sv.position
`

type GetCampaignScenariosRow struct {
	ScenarioCode   string
	ScenarioName   string
	ScenarioPrefix pgtype.Text
	Position       int32
	ImageUrl       pgtype.Text
}

func (q *Queries) GetCampaignScenarios(ctx context.Context, campaignCode pgtype.Text) ([]GetCampaignScenariosRow, error) {
	rows, err := q.db.Query(ctx, getCampaignScenarios, campaignCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCampaignScenariosRow
	for rows.Next() {
		var i GetCampaignScenariosRow
		if err := rows.Scan(
			&i.ScenarioCode,
			&i.ScenarioName,
			&i.ScenarioPrefix,
			&i.Position,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT
    cv.campaign_code,
    cv.campaign_name,
    cv.image_url
FROM campaign_view cv
ORDER BY cv.campaign_name
`

type ListCampaignsRow struct {
	CampaignCode string
	CampaignName string
	ImageUrl     pgtype.Text
}

func (q *Queries) ListCampaigns(ctx context.Context) ([]ListCampaignsRow, error) {
	rows, err := q.db.Query(ctx, listCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampaignsRow
	for rows.Next() {
		var i ListCampaignsRow
		if err := rows.Scan(&i.CampaignCode, &i.CampaignName, &i.ImageUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCampaign = `-- name: UpsertCampaign :exec
INSERT INTO campaign (campaign_code, campaign_name)
VALUES ($1, $2)
ON CONFLICT (campaign_code) DO UPDATE SET
    campaign_name = EXCLUDED.campaign_name,
    updated_at = NOW()
`

type UpsertCampaignParams struct {
	CampaignCode string
	CampaignName string
}

func (q *Queries) UpsertCampaign(ctx context.Context, arg UpsertCampaignParams) error {
	_, err := q.db.Exec(ctx, upsertCampaign, arg.CampaignCode, arg.CampaignName)
	return err
}

const upsertEncounterSetScenario = `-- name: UpsertEncounterSetScenario :exec
INSERT INTO encounter_set_scenario (encounter_code, scenario_code, position)
VALUES ($1, $2, $3)
ON CONFLICT (encounter_code, scenario_code) DO UPDATE SET
    position = EXCLUDED.position
`

type UpsertEncounterSetScenarioParams struct {
	EncounterCode string
	ScenarioCode  string
	Position      int32
}

func (q *Queries) UpsertEncounterSetScenario(ctx context.Context, arg UpsertEncounterSetScenarioParams) error {
	_, err := q.db.Exec(ctx, upsertEncounterSetScenario, arg.EncounterCode, arg.ScenarioCode, arg.Position)
	return err
}

const upsertScenario = `-- name: UpsertScenario :exec
INSERT INTO scenario (scenario_code, scenario_name, scenario_prefix, campaign_code, position)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (scenario_code) DO UPDATE SET
    scenario_name = EXCLUDED.scenario_name,
    scenario_prefix = EXCLUDED.scenario_prefix,
    campaign_code = EXCLUDED.campaign_code,
    position = EXCLUDED.position,
    updated_at = NOW()
`

type UpsertScenarioParams struct {
	ScenarioCode   string
	ScenarioName   string
	ScenarioPrefix pgtype.Text
	CampaignCode   pgtype.Text
	Position       int32
}

func (q *Queries) UpsertScenario(ctx context.Context, arg UpsertScenarioParams) error {
	_, err := q.db.Exec(ctx, upsertScenario,
		arg.ScenarioCode,
		arg.ScenarioName,
		arg.ScenarioPrefix,
		arg.CampaignCode,
		arg.Position,
	)
	return err
}
