// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCardByCode = `-- name: GetCardByCode :one
SELECT
    c.card_code,
    c.card_name,
    c.real_name,
    c.type_code,
    c.type_name,
    c.faction_code,
    c.faction_name,
    c.encounter_code,
    c.encounter_name,
    c.encounter_position,
    c.position,
    c.text,
    c.back_text,
    c.flavor,
    c.traits,
    c.url,
    c.imagesrc,
    c.backimagesrc,
    c.back_flavor,
    c.pack_code,
    c.pack_name,
    c.quantity,
    c.image_url
FROM card c
WHERE c.card_code = $1
`

type GetCardByCodeRow struct {
	CardCode          string
	CardName          string
	RealName          pgtype.Text
	TypeCode          string
	TypeName          string
	FactionCode       string
	FactionName       string
	EncounterCode     pgtype.Text
	EncounterName     pgtype.Text
	EncounterPosition pgtype.Int4
	Position          pgtype.Int4
	Text              pgtype.Text
	BackText          pgtype.Text
	Flavor            pgtype.Text
	Traits            []string
	Url               string
	Imagesrc          pgtype.Text
	Backimagesrc      pgtype.Text
	BackFlavor        pgtype.Text
	PackCode          string
	PackName          string
	Quantity          pgtype.Int4
	ImageUrl          pgtype.Text
}

func (q *Queries) GetCardByCode(ctx context.Context, cardCode string) (GetCardByCodeRow, error) {
	row := q.db.QueryRow(ctx, getCardByCode, cardCode)
	var i GetCardByCodeRow
	err := row.Scan(
		&i.CardCode,
		&i.CardName,
		&i.RealName,
		&i.TypeCode,
		&i.TypeName,
		&i.FactionCode,
		&i.FactionName,
		&i.EncounterCode,
		&i.EncounterName,
		&i.EncounterPosition,
		&i.Position,
		&i.Text,
		&i.BackText,
		&i.Flavor,
		&i.Traits,
		&i.Url,
		&i.Imagesrc,
		&i.Backimagesrc,
		&i.BackFlavor,
		&i.PackCode,
		&i.PackName,
		&i.Quantity,
		&i.ImageUrl,
	)
	return i, err
}

const getCardScenarios = `-- name: GetCardScenarios :many
SELECT
    s.scenario_code,
    s.scenario_name,
    s.campaign_code,
    ca.campaign_name
FROM encounter_set_scenario ess
JOIN scenario s ON ess.scenario_code = s.scenario_code
JOIN campaign ca ON s.campaign_code = ca.campaign_code
WHERE ess.encounter_code = $1
ORDER BY s.position
`

type GetCardScenariosRow struct {
	ScenarioCode string
	ScenarioName string
	CampaignCode pgtype.Text
	CampaignName string
}

func (q *Queries) GetCardScenarios(ctx context.Context, encounterCode string) ([]GetCardScenariosRow, error) {
	rows, err := q.db.Query(ctx, getCardScenarios, encounterCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCardScenariosRow
	for rows.Next() {
		var i GetCardScenariosRow
		if err := rows.Scan(
			&i.ScenarioCode,
			&i.ScenarioName,
			&i.CampaignCode,
			&i.CampaignName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCard = `-- name: UpsertCard :exec
INSERT INTO card (
    card_code, card_name, real_name, type_code, type_name,
    faction_code, faction_name, encounter_code, encounter_name,
    encounter_position, position, text, back_text, flavor, traits,
    url, imagesrc, backimagesrc, back_flavor, raw_data,
    pack_code, pack_name, quantity
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20,
    $21, $22, $23
) ON CONFLICT (card_code) DO UPDATE SET
    card_name = EXCLUDED.card_name,
    real_name = EXCLUDED.real_name,
    type_code = EXCLUDED.type_code,
    type_name = EXCLUDED.type_name,
    faction_code = EXCLUDED.faction_code,
    faction_name = EXCLUDED.faction_name,
    encounter_code = EXCLUDED.encounter_code,
    encounter_name = EXCLUDED.encounter_name,
    encounter_position = EXCLUDED.encounter_position,
    position = EXCLUDED.position,
    text = EXCLUDED.text,
    back_text = EXCLUDED.back_text,
    flavor = EXCLUDED.flavor,
    traits = EXCLUDED.traits,
    url = EXCLUDED.url,
    imagesrc = EXCLUDED.imagesrc,
    backimagesrc = EXCLUDED.backimagesrc,
    back_flavor = EXCLUDED.back_flavor,
    raw_data = EXCLUDED.raw_data,
    pack_code = EXCLUDED.pack_code,
    pack_name = EXCLUDED.pack_name,
    quantity = EXCLUDED.quantity,
    updated_at = NOW()
`

type UpsertCardParams struct {
	CardCode          string
	CardName          string
	RealName          pgtype.Text
	TypeCode          string
	TypeName          string
	FactionCode       string
	FactionName       string
	EncounterCode     pgtype.Text
	EncounterName     pgtype.Text
	EncounterPosition pgtype.Int4
	Position          pgtype.Int4
	Text              pgtype.Text
	BackText          pgtype.Text
	Flavor            pgtype.Text
	Traits            []string
	Url               string
	Imagesrc          pgtype.Text
	Backimagesrc      pgtype.Text
	BackFlavor        pgtype.Text
	RawData           []byte
	PackCode          string
	PackName          string
	Quantity          pgtype.Int4
}

func (q *Queries) UpsertCard(ctx context.Context, arg UpsertCardParams) error {
	_, err := q.db.Exec(ctx, upsertCard,
		arg.CardCode,
		arg.CardName,
		arg.RealName,
		arg.TypeCode,
		arg.TypeName,
		arg.FactionCode,
		arg.FactionName,
		arg.EncounterCode,
		arg.EncounterName,
		arg.EncounterPosition,
		arg.Position,
		arg.Text,
		arg.BackText,
		arg.Flavor,
		arg.Traits,
		arg.Url,
		arg.Imagesrc,
		arg.Backimagesrc,
		arg.BackFlavor,
		arg.RawData,
		arg.PackCode,
		arg.PackName,
		arg.Quantity,
	)
	return err
}
