// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: encounter_sets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEncounterSetByCode = `-- name: GetEncounterSetByCode :one
SELECT
    es.encounter_code,
    es.encounter_name,
    es.image_url
FROM encounter_set es
WHERE es.encounter_code = $1
`

type GetEncounterSetByCodeRow struct {
	EncounterCode pgtype.Text
	EncounterName pgtype.Text
	ImageUrl      pgtype.Text
}

func (q *Queries) GetEncounterSetByCode(ctx context.Context, encounterCode pgtype.Text) (GetEncounterSetByCodeRow, error) {
	row := q.db.QueryRow(ctx, getEncounterSetByCode, encounterCode)
	var i GetEncounterSetByCodeRow
	err := row.Scan(&i.EncounterCode, &i.EncounterName, &i.ImageUrl)
	return i, err
}

const getEncounterSetCards = `-- name: GetEncounterSetCards :many
SELECT
    c.card_code,
    c.card_name,
    c.type_code,
    c.type_name,
    c.traits,
    c.quantity,
    c.image_url
FROM card c
WHERE c.encounter_code = $1
ORDER BY c.card_code
`

type GetEncounterSetCardsRow struct {
	CardCode string
	CardName string
	TypeCode string
	TypeName string
	Traits   []string
	Quantity pgtype.Int4
	ImageUrl pgtype.Text
}

func (q *Queries) GetEncounterSetCards(ctx context.Context, encounterCode pgtype.Text) ([]GetEncounterSetCardsRow, error) {
	rows, err := q.db.Query(ctx, getEncounterSetCards, encounterCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEncounterSetCardsRow
	for rows.Next() {
		var i GetEncounterSetCardsRow
		if err := rows.Scan(
			&i.CardCode,
			&i.CardName,
			&i.TypeCode,
			&i.TypeName,
			&i.Traits,
			&i.Quantity,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEncounterSetScenarios = `-- name: GetEncounterSetScenarios :many
SELECT
    s.scenario_code,
    s.scenario_name,
    s.campaign_code,
    ca.campaign_name
FROM encounter_set_scenario ess
JOIN scenario s ON ess.scenario_code = s.scenario_code
JOIN campaign ca ON s.campaign_code = ca.campaign_code
WHERE ess.encounter_code = $1
ORDER BY s.position
`

type GetEncounterSetScenariosRow struct {
	ScenarioCode string
	ScenarioName string
	CampaignCode pgtype.Text
	CampaignName string
}

func (q *Queries) GetEncounterSetScenarios(ctx context.Context, encounterCode string) ([]GetEncounterSetScenariosRow, error) {
	rows, err := q.db.Query(ctx, getEncounterSetScenarios, encounterCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEncounterSetScenariosRow
	for rows.Next() {
		var i GetEncounterSetScenariosRow
		if err := rows.Scan(
			&i.ScenarioCode,
			&i.ScenarioName,
			&i.CampaignCode,
			&i.CampaignName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
