// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Campaign struct {
	CampaignCode string
	CampaignName string
	UpdatedAt    pgtype.Timestamp
}

type CampaignView struct {
	CampaignCode string
	CampaignName string
	UpdatedAt    pgtype.Timestamp
	ImageUrl     pgtype.Text
	TypeCode     pgtype.Text
	PackName     pgtype.Text
}

type Card struct {
	CardCode          string
	CardName          string
	RealName          pgtype.Text
	TypeCode          string
	TypeName          string
	FactionCode       string
	FactionName       string
	EncounterCode     pgtype.Text
	EncounterName     pgtype.Text
	EncounterPosition pgtype.Int4
	Position          pgtype.Int4
	Text              pgtype.Text
	BackText          pgtype.Text
	Flavor            pgtype.Text
	Traits            []string
	Url               string
	Imagesrc          pgtype.Text
	Backimagesrc      pgtype.Text
	BackFlavor        pgtype.Text
	RawData           []byte
	PackCode          string
	PackName          string
	UpdatedAt         pgtype.Timestamp
	Quantity          pgtype.Int4
	ImageUrl          pgtype.Text
}

type EncounterSet struct {
	EncounterCode pgtype.Text
	EncounterName pgtype.Text
	ImageUrl      pgtype.Text
	TypeCode      string
	PackName      string
}

type EncounterSetScenario struct {
	EncounterCode string
	ScenarioCode  string
	Position      int32
}

type Pack struct {
	PackCode string
	PackName string
	ImageUrl pgtype.Text
	TypeCode string
}

type Scenario struct {
	ScenarioCode   string
	ScenarioName   string
	ScenarioPrefix pgtype.Text
	CampaignCode   pgtype.Text
	UpdatedAt      pgtype.Timestamp
	Position       int32
}

type ScenarioView struct {
	ScenarioCode   string
	ScenarioName   string
	ScenarioPrefix pgtype.Text
	CampaignCode   pgtype.Text
	UpdatedAt      pgtype.Timestamp
	Position       int32
	ImageUrl       pgtype.Text
	TypeCode       pgtype.Text
	PackName       pgtype.Text
}

type SearchView struct {
	Type     string
	Code     string
	Name     string
	ImageUrl pgtype.Text
	TypeCode string
	PackName string
}

type Trait struct {
	TraitName interface{}
	ImageUrl  pgtype.Text
	TypeCode  string
	PackName  string
}
