// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scenarios.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getScenarioByCode = `-- name: GetScenarioByCode :one
SELECT
    s.scenario_code,
    s.scenario_name,
    s.scenario_prefix,
    s.campaign_code,
    s.position,
    sv.image_url
FROM scenario s
JOIN scenario_view sv ON s.scenario_code = sv.scenario_code
WHERE s.scenario_code = $1
`

type GetScenarioByCodeRow struct {
	ScenarioCode   string
	ScenarioName   string
	ScenarioPrefix pgtype.Text
	CampaignCode   pgtype.Text
	Position       int32
	ImageUrl       pgtype.Text
}

func (q *Queries) GetScenarioByCode(ctx context.Context, scenarioCode string) (GetScenarioByCodeRow, error) {
	row := q.db.QueryRow(ctx, getScenarioByCode, scenarioCode)
	var i GetScenarioByCodeRow
	err := row.Scan(
		&i.ScenarioCode,
		&i.ScenarioName,
		&i.ScenarioPrefix,
		&i.CampaignCode,
		&i.Position,
		&i.ImageUrl,
	)
	return i, err
}

const getScenarioCards = `-- name: GetScenarioCards :many
SELECT
    c.card_code,
    c.card_name,
    c.type_code,
    c.type_name,
    c.encounter_code,
    c.traits,
    c.quantity,
    c.image_url
FROM encounter_set_scenario ess
JOIN card c ON ess.encounter_code = c.encounter_code
WHERE ess.scenario_code = $1
ORDER BY ess.position, c.card_code
`

type GetScenarioCardsRow struct {
	CardCode      string
	CardName      string
	TypeCode      string
	TypeName      string
	EncounterCode pgtype.Text
	Traits        []string
	Quantity      pgtype.Int4
	ImageUrl      pgtype.Text
}

func (q *Queries) GetScenarioCards(ctx context.Context, scenarioCode string) ([]GetScenarioCardsRow, error) {
	rows, err := q.db.Query(ctx, getScenarioCards, scenarioCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetScenarioCardsRow
	for rows.Next() {
		var i GetScenarioCardsRow
		if err := rows.Scan(
			&i.CardCode,
			&i.CardName,
			&i.TypeCode,
			&i.TypeName,
			&i.EncounterCode,
			&i.Traits,
			&i.Quantity,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScenarioEncounterSets = `-- name: GetScenarioEncounterSets :many
SELECT
    es.encounter_code,
    es.encounter_name,
    ess.position
FROM encounter_set_scenario ess
JOIN encounter_set es ON ess.encounter_code = es.encounter_code
WHERE ess.scenario_code = $1
ORDER BY ess.position
`

type GetScenarioEncounterSetsRow struct {
	EncounterCode pgtype.Text
	EncounterName pgtype.Text
	Position      int32
}

func (q *Queries) GetScenarioEncounterSets(ctx context.Context, scenarioCode string) ([]GetScenarioEncounterSetsRow, error) {
	rows, err := q.db.Query(ctx, getScenarioEncounterSets, scenarioCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetScenarioEncounterSetsRow
	for rows.Next() {
		var i GetScenarioEncounterSetsRow
		if err := rows.Scan(&i.EncounterCode, &i.EncounterName, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
