// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package db

import (
	"context"
)

const search = `-- name: Search :many
SELECT
    type,
    code,
    name,
    image_url,
    type_code,
    pack_name
FROM search_view
WHERE word_similarity($1, name) > 0.3
ORDER BY word_similarity($1, name) DESC, name ASC
LIMIT $2
`

type SearchParams struct {
	WordSimilarity string
	Limit          int32
}

func (q *Queries) Search(ctx context.Context, arg SearchParams) ([]SearchView, error) {
	rows, err := q.db.Query(ctx, search, arg.WordSimilarity, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchView
	for rows.Next() {
		var i SearchView
		if err := rows.Scan(
			&i.Type,
			&i.Code,
			&i.Name,
			&i.ImageUrl,
			&i.TypeCode,
			&i.PackName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
