// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const search = `-- name: Search :many
SELECT
    type,
    code,
    name,
    image_url
FROM search_view
WHERE full_text_search @@ to_tsquery('english', $1)
ORDER BY ts_rank(full_text_search, to_tsquery('english', $1)) DESC
LIMIT $2
`

type SearchParams struct {
	ToTsquery string
	Limit     int32
}

type SearchRow struct {
	Type     string
	Code     string
	Name     string
	ImageUrl pgtype.Text
}

func (q *Queries) Search(ctx context.Context, arg SearchParams) ([]SearchRow, error) {
	rows, err := q.db.Query(ctx, search, arg.ToTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchRow
	for rows.Next() {
		var i SearchRow
		if err := rows.Scan(
			&i.Type,
			&i.Code,
			&i.Name,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
